### PR TITLE
Allow gem to parse JSON files

### PR DESCRIPTION
**Pull request by fpringvaldsen**
Allow the ruby hocon gem to parse JSON files. Previously,
attempting to parse a JSON file would lead to an uninitialized
constant error.

### CODE REVIEW

**Comment by mckern** [comment]
did you mean to include `config.json` in here?

**Comment by mckern** [comment]
Actually, looking at it, can you sanitize that JSON a little bit to make it a bit more generic?

**Comment by fpringvaldsen** [comment]
@mckern I've removed `config.json` and sanitized the test fixtures to be about puppets.

**Comment by mckern** [comment]
blue

**Pull request merged**
